
const DESTINATIONS = [
  { id:'taj-mahal', name:'Taj Mahal', country:'India', city:'Agra', coords:[27.1751,78.0421], cat:'cultural', rating:4.8, emoji:'🕌',
    desc:'Iconic ivory-white marble mausoleum and UNESCO World Heritage Site.',
    highlights:['Sunrise view','Garden symmetry','Moonlight nights'],
    challenge:'Find the optical illusion — the minarets tilt outward!',
    reward:150, badge:'🏛️ Mughal Explorer',
    pricing:[{item:'Entry (Local)',local:50,tourist:1100,cur:'INR'},{item:'Guide',local:500,tourist:2000,cur:'INR'},{item:'Auto Rickshaw',local:30,tourist:200,cur:'INR'}],
    scams:['Avoid unofficial guides at the gate','Skip "marble" souvenir sellers'],
    guides:[{name:'Rajesh K.',rating:4.9,langs:['Hindi','English','French'],price:500,cur:'INR',spec:'Mughal History',avatar:'👳‍♂️'}]},
  { id:'eiffel-tower', name:'Eiffel Tower', country:'France', city:'Paris', coords:[48.8584,2.2945], cat:'cultural', rating:4.7, emoji:'🗼',
    desc:'Wrought-iron lattice tower and global icon of France.',
    highlights:['Summit view','Night sparkle show','Champagne bar'],
    challenge:'Count the arches on the first floor — there are exactly 4!',
    reward:130, badge:'🇫🇷 Parisian',
    pricing:[{item:'Summit Ticket',local:26,tourist:26,cur:'EUR'},{item:'Café Meal',local:12,tourist:35,cur:'EUR'},{item:'Seine Cruise',local:10,tourist:18,cur:'EUR'}],
    scams:['Bracelet scammers near Trocadéro','Fake petition signers'],
    guides:[{name:'Marie D.',rating:4.8,langs:['French','English','Spanish'],price:60,cur:'EUR',spec:'Art & Architecture',avatar:'👩'}]},
  { id:'machu-picchu', name:'Machu Picchu', country:'Peru', city:'Cusco', coords:[-13.1631,-72.5450], cat:'adventure', rating:4.9, emoji:'🏔️',
    desc:'15th-century Inca citadel set high in the Andes Mountains.',
    highlights:['Sun Gate trek','Temple of the Sun','Llama encounters'],
    challenge:'Spot the sacred rock shaped like a mountain behind it!',
    reward:200, badge:'🦙 Inca Seeker',
    pricing:[{item:'Entry',local:64,tourist:152,cur:'PEN'},{item:'Bus Ride',local:30,tourist:80,cur:'PEN'},{item:'Lunch',local:15,tourist:50,cur:'PEN'}],
    scams:['Overpriced bus tickets from unofficial sellers','Fake tour agencies in Cusco'],
    guides:[{name:'Carlos M.',rating:4.9,langs:['Spanish','English','Quechua'],price:120,cur:'PEN',spec:'Inca Civilization',avatar:'👨'}]},
  { id:'great-wall', name:'Great Wall', country:'China', city:'Beijing', coords:[40.4319,116.5704], cat:'cultural', rating:4.8, emoji:'🏯',
    desc:'Ancient series of walls stretching over 13,000 miles.',
    highlights:['Mutianyu section','Toboggan ride down','Watchtower views'],
    challenge:'Find the watchtower with the best panoramic view!',
    reward:170, badge:'🐉 Dragon Walker',
    pricing:[{item:'Entry (Mutianyu)',local:40,tourist:40,cur:'CNY'},{item:'Cable Car',local:100,tourist:120,cur:'CNY'},{item:'Lunch',local:25,tourist:80,cur:'CNY'}],
    scams:['Avoid "tea ceremony" invitations near tourist areas','Overpriced taxi rides'],
    guides:[{name:'Wei L.',rating:4.7,langs:['Mandarin','English'],price:300,cur:'CNY',spec:'Chinese History',avatar:'👨'}]},
  { id:'colosseum', name:'Colosseum', country:'Italy', city:'Rome', coords:[41.8902,12.4922], cat:'cultural', rating:4.7, emoji:'🏟️',
    desc:'Ancient amphitheatre and icon of Imperial Rome.',
    highlights:['Underground tunnels','Arena floor','Night tours'],
    challenge:'Find the cross marking where gladiators entered!',
    reward:140, badge:'⚔️ Gladiator',
    pricing:[{item:'Entry',local:16,tourist:16,cur:'EUR'},{item:'Pasta nearby',local:8,tourist:22,cur:'EUR'},{item:'Gelato',local:2.5,tourist:6,cur:'EUR'}],
    scams:['Fake gladiator photo ops charging €20+','Overpriced restaurants right at the plaza'],
    guides:[{name:'Luca R.',rating:4.8,langs:['Italian','English','German'],price:50,cur:'EUR',spec:'Roman Empire',avatar:'👨'}]},
  { id:'angkor-wat', name:'Angkor Wat', country:'Cambodia', city:'Siem Reap', coords:[13.4125,103.8670], cat:'cultural', rating:4.9, emoji:'🛕',
    desc:'Largest religious monument in the world, a temple complex.',
    highlights:['Sunrise reflections','Bayon faces','Ta Prohm tree roots'],
    challenge:'Count the smiling faces at Bayon Temple!',
    reward:180, badge:'🌅 Temple Raider',
    pricing:[{item:'1-Day Pass',local:0,tourist:37,cur:'USD'},{item:'Tuk-Tuk Tour',local:5,tourist:20,cur:'USD'},{item:'Dinner',local:3,tourist:12,cur:'USD'}],
    scams:['Children selling postcards as distraction','Unofficial sunrise tour guides'],
    guides:[{name:'Sokha P.',rating:4.9,langs:['Khmer','English','Japanese'],price:35,cur:'USD',spec:'Khmer History',avatar:'👩'}]},
  { id:'santorini', name:'Santorini', country:'Greece', city:'Oia', coords:[36.4618,25.3753], cat:'nature', rating:4.8, emoji:'🏝️',
    desc:'Stunning volcanic island with iconic white-blue architecture.',
    highlights:['Oia sunset','Caldera views','Red Beach'],
    challenge:'Find the famous blue dome church for the perfect photo!',
    reward:120, badge:'🌊 Aegean Voyager',
    pricing:[{item:'Ferry from Athens',local:35,tourist:60,cur:'EUR'},{item:'Dinner',local:15,tourist:40,cur:'EUR'},{item:'Wine Tasting',local:10,tourist:25,cur:'EUR'}],
    scams:['Overpriced donkey rides','Unmarked restaurant surcharges'],
    guides:[{name:'Elena K.',rating:4.7,langs:['Greek','English'],price:50,cur:'EUR',spec:'Island Culture',avatar:'👩'}]},
  { id:'pyramids-giza', name:'Pyramids of Giza', country:'Egypt', city:'Cairo', coords:[29.9792,31.1342], cat:'cultural', rating:4.8, emoji:'🔺',
    desc:'Ancient pyramid complex and the last surviving ancient wonder.',
    highlights:['Great Pyramid interior','Sphinx','Sound & Light Show'],
    challenge:'Stand at the spot where all 3 pyramids align perfectly!',
    reward:190, badge:'🐫 Pharaoh Finder',
    pricing:[{item:'Entry',local:30,tourist:200,cur:'EGP'},{item:'Camel Ride',local:50,tourist:300,cur:'EGP'},{item:'Museum',local:20,tourist:200,cur:'EGP'}],
    scams:['Free camel ride that demands payment','Fake antiquity sellers'],
    guides:[{name:'Ahmed H.',rating:4.8,langs:['Arabic','English','French'],price:200,cur:'EGP',spec:'Ancient Egypt',avatar:'👳'}]},
  { id:'grand-canyon', name:'Grand Canyon', country:'USA', city:'Arizona', coords:[36.1069,-112.1129], cat:'nature', rating:4.9, emoji:'🏜️',
    desc:'Steep-sided canyon carved by the Colorado River.',
    highlights:['South Rim views','Bright Angel Trail','Skywalk'],
    challenge:'Spot the Colorado River from 3 different viewpoints!',
    reward:160, badge:'🦅 Canyon Explorer',
    pricing:[{item:'Park Entry',local:35,tourist:35,cur:'USD'},{item:'Skywalk',local:47,tourist:47,cur:'USD'},{item:'Mule Ride',local:150,tourist:150,cur:'USD'}],
    scams:['Helicopter tours with hidden fees','Souvenir shops with extreme markups'],
    guides:[{name:'Jake T.',rating:4.7,langs:['English','Spanish'],price:80,cur:'USD',spec:'Geology',avatar:'👨'}]},
  { id:'sydney-opera', name:'Sydney Opera House', country:'Australia', city:'Sydney', coords:[-33.8568,151.2153], cat:'cultural', rating:4.7, emoji:'🎭',
    desc:'Multi-venue performing arts centre with iconic sail design.',
    highlights:['Guided backstage tour','Harbour Bridge view','Evening show'],
    challenge:'Find the artwork hidden in the underground corridors!',
    reward:110, badge:'🎵 Opera Star',
    pricing:[{item:'Guided Tour',local:43,tourist:43,cur:'AUD'},{item:'Show Ticket',local:70,tourist:120,cur:'AUD'},{item:'Harbour Ferry',local:6,tourist:6,cur:'AUD'}],
    scams:['Overpriced taxis from airport','Unlicensed harbour cruise sellers'],
    guides:[{name:'Sarah W.',rating:4.6,langs:['English'],price:60,cur:'AUD',spec:'Performing Arts',avatar:'👩'}]},
  { id:'petra', name:'Petra', country:'Jordan', city:'Wadi Musa', coords:[30.3285,35.4444], cat:'adventure', rating:4.9, emoji:'🏛️',
    desc:'Ancient city carved into rose-red cliff faces.',
    highlights:['The Treasury','Monastery hike','Petra by Night'],
    challenge:'Reach the Monastery — 800 steps to glory!',
    reward:200, badge:'🌹 Rose City',
    pricing:[{item:'1-Day Pass',local:1,tourist:50,cur:'JOD'},{item:'Horse Ride',local:5,tourist:20,cur:'JOD'},{item:'Petra by Night',local:12,tourist:17,cur:'JOD'}],
    scams:['Horse riders demanding extra tips','Overpriced souvenir shops inside'],
    guides:[{name:'Omar S.',rating:4.9,langs:['Arabic','English'],price:30,cur:'JOD',spec:'Nabataean History',avatar:'👳'}]},
  { id:'bali', name:'Bali Temples', country:'Indonesia', city:'Bali', coords:[-8.3405,115.0920], cat:'nature', rating:4.7, emoji:'🌺',
    desc:'Island paradise with ancient temples and rice terraces.',
    highlights:['Uluwatu Temple sunset','Tegallalang Rice Terraces','Sacred Monkey Forest'],
    challenge:'Photograph all 3 major temple sunset views!',
    reward:130, badge:'🌴 Island Spirit',
    pricing:[{item:'Temple Entry',local:5000,tourist:50000,cur:'IDR'},{item:'Massage',local:50000,tourist:200000,cur:'IDR'},{item:'Nasi Goreng',local:15000,tourist:60000,cur:'IDR'}],
    scams:['Money changers giving bad rates','Overpriced taxi meters'],
    guides:[{name:'Wayan S.',rating:4.8,langs:['Indonesian','English'],price:300000,cur:'IDR',spec:'Hindu Culture',avatar:'👨'}]},
  { id:'dubai-burj', name:'Burj Khalifa', country:'UAE', city:'Dubai', coords:[25.1972,55.2744], cat:'cultural', rating:4.6, emoji:'🌆',
    desc:'World\'s tallest building at 828 meters.',
    highlights:['At The Top observation','Dubai Fountain','Sky lounge'],
    challenge:'Watch the fountain show from the 148th floor!',
    reward:120, badge:'✨ Sky High',
    pricing:[{item:'Observation Deck',local:149,tourist:149,cur:'AED'},{item:'Lunch',local:40,tourist:120,cur:'AED'},{item:'Taxi',local:15,tourist:15,cur:'AED'}],
    scams:['Unofficial ticket resellers online','Fake desert safari deals'],
    guides:[{name:'Fatima A.',rating:4.7,langs:['Arabic','English','Hindi'],price:200,cur:'AED',spec:'Modern Architecture',avatar:'👩'}]},
  { id:'mount-fuji', name:'Mount Fuji', country:'Japan', city:'Fujinomiya', coords:[35.3606,138.7274], cat:'nature', rating:4.8, emoji:'🗻',
    desc:'Japan\'s highest peak and sacred volcano.',
    highlights:['Sunrise from summit','Lake Kawaguchi view','Fifth Station'],
    challenge:'Capture the perfect reflection in Lake Kawaguchi!',
    reward:170, badge:'🌸 Fuji Climber',
    pricing:[{item:'Bus to 5th Station',local:1500,tourist:2100,cur:'JPY'},{item:'Mountain Hut',local:5000,tourist:7000,cur:'JPY'},{item:'Ramen',local:800,tourist:1500,cur:'JPY'}],
    scams:['Unlicensed mountain guides','Overpriced "lucky charms" at stations'],
    guides:[{name:'Yuki T.',rating:4.9,langs:['Japanese','English'],price:15000,cur:'JPY',spec:'Mountain Guide',avatar:'👩'}]},
  { id:'christ-redeemer', name:'Christ the Redeemer', country:'Brazil', city:'Rio de Janeiro', coords:[-22.9519,-43.2105], cat:'cultural', rating:4.7, emoji:'✝️',
    desc:'Iconic Art Deco statue atop Corcovado mountain.',
    highlights:['Panoramic views','Sunset visits','Tijuca Forest trail'],
    challenge:'Find the spot where arms span matches the horizon!',
    reward:140, badge:'🇧🇷 Rio Legend',
    pricing:[{item:'Train+Entry',local:40,tourist:80,cur:'BRL'},{item:'Açaí Bowl',local:10,tourist:30,cur:'BRL'},{item:'Taxi',local:20,tourist:60,cur:'BRL'}],
    scams:['Overpriced van rides up the mountain','Pickpockets near the base'],
    guides:[{name:'Pedro L.',rating:4.7,langs:['Portuguese','English','Spanish'],price:100,cur:'BRL',spec:'Rio Culture',avatar:'👨'}]},
  { id:'halong-bay', name:'Ha Long Bay', country:'Vietnam', city:'Quang Ninh', coords:[20.9101,107.1839], cat:'nature', rating:4.8, emoji:'⛵',
    desc:'Emerald waters with thousands of towering limestone islands.',
    highlights:['Overnight cruise','Kayaking','Sung Sot Cave'],
    challenge:'Find the island that looks like a fighting cock!',
    reward:160, badge:'🐲 Dragon Bay',
    pricing:[{item:'Day Cruise',local:500000,tourist:1500000,cur:'VND'},{item:'Kayak Rental',local:50000,tourist:200000,cur:'VND'},{item:'Seafood Meal',local:80000,tourist:300000,cur:'VND'}],
    scams:['Budget cruise boats with poor safety','Hidden fees on boat tours'],
    guides:[{name:'Linh N.',rating:4.8,langs:['Vietnamese','English'],price:400000,cur:'VND',spec:'Marine Guide',avatar:'👩'}]},
  { id:'barcelona-sagrada', name:'Sagrada Família', country:'Spain', city:'Barcelona', coords:[41.4036,2.1744], cat:'cultural', rating:4.8, emoji:'⛪',
    desc:'Gaudí\'s unfinished masterpiece basilica.',
    highlights:['Tower views','Light through stained glass','Nativity façade'],
    challenge:'Find Gaudí\'s signature nature-inspired columns!',
    reward:135, badge:'🎨 Gaudí Fan',
    pricing:[{item:'Entry',local:26,tourist:26,cur:'EUR'},{item:'Tower Access',local:36,tourist:36,cur:'EUR'},{item:'Tapas',local:8,tourist:20,cur:'EUR'}],
    scams:['Unofficial ticket scalpers','Pickpockets on La Rambla'],
    guides:[{name:'Marta G.',rating:4.8,langs:['Spanish','English','Catalan'],price:45,cur:'EUR',spec:'Gaudí Architecture',avatar:'👩'}]},
  { id:'serengeti', name:'Serengeti', country:'Tanzania', city:'Arusha', coords:[-2.3333,34.8333], cat:'adventure', rating:4.9, emoji:'🦁',
    desc:'Vast ecosystem famous for the Great Migration.',
    highlights:['Big Five safari','Great Migration','Balloon ride'],
    challenge:'Spot all the Big Five in one safari day!',
    reward:250, badge:'🦁 Safari King',
    pricing:[{item:'Park Fee/day',local:10,tourist:60,cur:'USD'},{item:'Safari Vehicle',local:100,tourist:300,cur:'USD'},{item:'Lodge/night',local:50,tourist:200,cur:'USD'}],
    scams:['Unlicensed safari operators','Hidden park fee surcharges'],
    guides:[{name:'Joseph M.',rating:4.9,langs:['Swahili','English'],price:80,cur:'USD',spec:'Wildlife Expert',avatar:'👨'}]},
  { id:'istanbul-sophia', name:'Hagia Sophia', country:'Turkey', city:'Istanbul', coords:[41.0086,28.9802], cat:'cultural', rating:4.8, emoji:'🕌',
    desc:'Byzantine cathedral turned mosque — architectural marvel.',
    highlights:['Massive dome','Byzantine mosaics','Blue Mosque nearby'],
    challenge:'Find the "weeping column" and make a wish!',
    reward:140, badge:'🌙 Ottoman Explorer',
    pricing:[{item:'Entry',local:0,tourist:0,cur:'TRY'},{item:'Bosphorus Cruise',local:50,tourist:200,cur:'TRY'},{item:'Kebab Meal',local:80,tourist:250,cur:'TRY'}],
    scams:['Shoe shine "drop" scam','Overpriced carpet shop invitations'],
    guides:[{name:'Ayşe B.',rating:4.7,langs:['Turkish','English','Arabic'],price:300,cur:'TRY',spec:'Byzantine & Ottoman',avatar:'👩'}]},
  { id:'cape-town', name:'Table Mountain', country:'South Africa', city:'Cape Town', coords:[-33.9625,18.4039], cat:'nature', rating:4.8, emoji:'⛰️',
    desc:'Flat-topped mountain offering panoramic city and ocean views.',
    highlights:['Cable car ride','Hiking trails','Sunset views'],
    challenge:'Find the rock hyrax — a cute mountain-dwelling mammal!',
    reward:130, badge:'🌍 Cape Discoverer',
    pricing:[{item:'Cable Car',local:190,tourist:395,cur:'ZAR'},{item:'Lunch',local:100,tourist:300,cur:'ZAR'},{item:'Wine Tasting',local:50,tourist:150,cur:'ZAR'}],
    scams:['Unofficial parking attendants','Counterfeit tour operators'],
    guides:[{name:'Thabo N.',rating:4.8,langs:['English','Afrikaans','Zulu'],price:400,cur:'ZAR',spec:'Nature & Wildlife',avatar:'👨'}]}
];

const CATEGORIES = [
  {id:'all',label:'All',icon:'🌍'},
  {id:'cultural',label:'Cultural',icon:'🏛️'},
  {id:'nature',label:'Nature',icon:'🌿'},
  {id:'adventure',label:'Adventure',icon:'⛰️'}
];
