
const LANGS = {
  en:{name:'English',flag:'🇬🇧'},es:{name:'Español',flag:'🇪🇸'},fr:{name:'Français',flag:'🇫🇷'},
  de:{name:'Deutsch',flag:'🇩🇪'},it:{name:'Italiano',flag:'🇮🇹'},pt:{name:'Português',flag:'🇧🇷'},
  zh:{name:'中文',flag:'🇨🇳'},ja:{name:'日本語',flag:'🇯🇵'},ko:{name:'한국어',flag:'🇰🇷'},
  hi:{name:'हिन्दी',flag:'🇮🇳'},bn:{name:'বাংলা',flag:'🇧🇩'},ar:{name:'العربية',flag:'🇸🇦'},ru:{name:'Русский',flag:'🇷🇺'},
  th:{name:'ไทย',flag:'🇹🇭'},tr:{name:'Türkçe',flag:'🇹🇷'},id:{name:'Bahasa',flag:'🇮🇩'},vi:{name:'Tiếng Việt',flag:'🇻🇳'}
};

const T = {
  en:{heroTag:'🧭 Your Adventure Awaits',heroTitle:'Discover Hidden Treasures Around The World',heroSub:'A treasure-hunt experience guiding you through top destinations with verified pricing, local guides, and epic rewards.',btnExplore:'Explore Map',btnHunt:'Start Hunt',statDest:'Destinations',statCountry:'Countries',statReward:'Rewards',navMap:'Map',navHunt:'Treasure Hunt',navPrice:'Pricing',navGuide:'Guides',navReward:'Rewards',mapTag:'WORLD EXPLORER',mapTitle:'Interactive World Map',mapDesc:'Pin any destination, toggle satellite view, and explore every corner of the globe.',filterAll:'All',filterCultural:'Cultural',filterNature:'Nature',filterAdventure:'Adventure',mapStandard:'Standard',mapSatellite:'Satellite',huntTag:'TREASURE HUNT',huntTitle:'Collect Treasures Worldwide',huntDesc:'Complete challenges at each destination to earn points and unlock exclusive badges.',priceTag:'VERIFIED PRICING',priceTitle:'Avoid Tourist Scams',priceDesc:'Compare real local prices vs inflated tourist prices. Travel smart, save money.',thItem:'Item / Service',thLocal:'Local Price',thTourist:'Tourist Price',thSave:'You Save',guideTag:'LOCAL GUIDES',guideTitle:'Hire Trusted Guides',guideDesc:'Book verified local experts who speak your language and know every hidden gem.',rewardTag:'YOUR REWARDS',rewardTitle:'Rewards Dashboard',rewardDesc:'Track your points, badges, and treasure hunt progress.',rwdPoints:'Total Points',rwdBadges:'Badges Earned',rwdPlaces:'Places Visited',rwdRank:'Explorer Rank',badgesTitle:'Your Badges',selectDest:'Select a destination on the map to see details',footerTag:'WanderQuest',footerAbout:'About',footerContact:'Contact',footerPrivacy:'Privacy',footerCopy:'© 2026 WanderQuest. All rights reserved.',viewSat:'Satellite View',hireNow:'Hire Now',viewPricing:'View Pricing',challenge:'Challenge',scamAlerts:'Scam Alerts',highlights:'Highlights',perDay:'/day',booked:'Booked!',langTitle:'Choose Your Language',close:'Close',completed:'Completed!',locked:'Locked'},
  es:{heroTag:'🧭 Tu Aventura Te Espera',heroTitle:'Descubre Tesoros Ocultos En El Mundo',heroSub:'Una experiencia de búsqueda del tesoro con precios verificados, guías locales y recompensas épicas.',btnExplore:'Explorar Mapa',btnHunt:'Iniciar Caza',statDest:'Destinos',statCountry:'Países',statReward:'Premios',navMap:'Mapa',navHunt:'Búsqueda',navPrice:'Precios',navGuide:'Guías',navReward:'Premios',mapTag:'EXPLORADOR MUNDIAL',mapTitle:'Mapa Mundial Interactivo',mapDesc:'Fija cualquier destino, cambia a vista satelital y explora cada rincón.',filterAll:'Todos',filterCultural:'Cultural',filterNature:'Naturaleza',filterAdventure:'Aventura',mapStandard:'Estándar',mapSatellite:'Satélite',huntTag:'BÚSQUEDA DEL TESORO',huntTitle:'Colecciona Tesoros',huntDesc:'Completa desafíos en cada destino para ganar puntos e insignias.',priceTag:'PRECIOS VERIFICADOS',priceTitle:'Evita Estafas Turísticas',priceDesc:'Compara precios locales reales vs precios inflados.',thItem:'Artículo / Servicio',thLocal:'Precio Local',thTourist:'Precio Turista',thSave:'Ahorras',guideTag:'GUÍAS LOCALES',guideTitle:'Contrata Guías Locales',guideDesc:'Reserva expertos verificados que hablan tu idioma.',rewardTag:'TUS PREMIOS',rewardTitle:'Panel de Premios',rewardDesc:'Rastrea tus puntos, insignias y progreso.',rwdPoints:'Puntos Totales',rwdBadges:'Insignias',rwdPlaces:'Lugares Visitados',rwdRank:'Rango Explorador',badgesTitle:'Tus Insignias',selectDest:'Selecciona un destino en el mapa',footerTag:'WanderQuest',footerAbout:'Acerca de',footerContact:'Contacto',footerPrivacy:'Privacidad',footerCopy:'© 2026 WanderQuest. Todos los derechos reservados.',viewSat:'Vista Satélite',hireNow:'Contratar',viewPricing:'Ver Precios',challenge:'Desafío',scamAlerts:'Alertas de Estafa',highlights:'Destacados',perDay:'/día',booked:'¡Reservado!',langTitle:'Elige Tu Idioma',close:'Cerrar',completed:'¡Completado!',locked:'Bloqueado'},
  fr:{heroTag:'🧭 Votre Aventure Vous Attend',heroTitle:'Découvrez Des Trésors Cachés Dans Le Monde',heroSub:'Une chasse au trésor avec prix vérifiés, guides locaux et récompenses épiques.',btnExplore:'Explorer la Carte',btnHunt:'Commencer',statDest:'Destinations',statCountry:'Pays',statReward:'Récompenses',navMap:'Carte',navHunt:'Chasse',navPrice:'Prix',navGuide:'Guides',navReward:'Récompenses',mapTag:'EXPLORATEUR MONDIAL',mapTitle:'Carte Mondiale Interactive',mapDesc:'Épinglez une destination et explorez en vue satellite.',filterAll:'Tous',filterCultural:'Culturel',filterNature:'Nature',filterAdventure:'Aventure',mapStandard:'Standard',mapSatellite:'Satellite',huntTag:'CHASSE AU TRÉSOR',huntTitle:'Collectionnez Des Trésors',huntDesc:'Relevez des défis pour gagner des points et badges.',priceTag:'PRIX VÉRIFIÉS',priceTitle:'Évitez Les Arnaques',priceDesc:'Comparez les vrais prix locaux vs les prix touristiques.',thItem:'Article / Service',thLocal:'Prix Local',thTourist:'Prix Touriste',thSave:'Économie',guideTag:'GUIDES LOCAUX',guideTitle:'Engagez Des Guides Locaux',guideDesc:'Réservez des experts vérifiés parlant votre langue.',rewardTag:'VOS RÉCOMPENSES',rewardTitle:'Tableau de Bord',rewardDesc:'Suivez vos points et badges.',rwdPoints:'Points Totaux',rwdBadges:'Badges Gagnés',rwdPlaces:'Lieux Visités',rwdRank:'Rang Explorateur',badgesTitle:'Vos Badges',selectDest:'Sélectionnez une destination',footerTag:'WanderQuest',footerAbout:'À propos',footerContact:'Contact',footerPrivacy:'Confidentialité',footerCopy:'© 2026 WanderQuest. Tous droits réservés.',viewSat:'Vue Satellite',hireNow:'Engager',viewPricing:'Voir Prix',challenge:'Défi',scamAlerts:'Alertes Arnaque',highlights:'Points Forts',perDay:'/jour',booked:'Réservé!',langTitle:'Choisissez Votre Langue',close:'Fermer',completed:'Terminé!',locked:'Verrouillé'},
  hi:{heroTag:'🧭 आपका रोमांच इंतजार कर रहा है',heroTitle:'दुनिया भर में छिपे खजाने खोजें',heroSub:'सत्यापित कीमतों, स्थानीय गाइड और शानदार पुरस्कारों के साथ खजाने की खोज।',btnExplore:'मानचित्र देखें',btnHunt:'खोज शुरू करें',statDest:'गंतव्य',statCountry:'देश',statReward:'पुरस्कार',navMap:'मानचित्र',navHunt:'खजाना खोज',navPrice:'मूल्य',navGuide:'गाइड',navReward:'पुरस्कार',mapTag:'विश्व खोजकर्ता',mapTitle:'इंटरैक्टिव विश्व मानचित्र',mapDesc:'किसी भी गंतव्य को पिन करें और उपग्रह दृश्य देखें।',filterAll:'सभी',filterCultural:'सांस्कृतिक',filterNature:'प्रकृति',filterAdventure:'साहसिक',mapStandard:'मानक',mapSatellite:'उपग्रह',huntTag:'खजाना खोज',huntTitle:'दुनिया भर में खजाने इकट्ठा करें',huntDesc:'अंक और बैज अर्जित करने के लिए चुनौतियाँ पूरी करें।',priceTag:'सत्यापित मूल्य',priceTitle:'पर्यटक घोटालों से बचें',priceDesc:'वास्तविक स्थानीय कीमतों की तुलना करें।',thItem:'वस्तु / सेवा',thLocal:'स्थानीय मूल्य',thTourist:'पर्यटक मूल्य',thSave:'बचत',guideTag:'स्थानीय गाइड',guideTitle:'विश्वसनीय गाइड किराए पर लें',guideDesc:'सत्यापित स्थानीय विशेषज्ञों को बुक करें।',rewardTag:'आपके पुरस्कार',rewardTitle:'पुरस्कार डैशबोर्ड',rewardDesc:'अपने अंक और बैज ट्रैक करें।',rwdPoints:'कुल अंक',rwdBadges:'बैज अर्जित',rwdPlaces:'स्थान देखे',rwdRank:'खोजकर्ता रैंक',badgesTitle:'आपके बैज',selectDest:'विवरण देखने के लिए गंतव्य चुनें',footerTag:'WanderQuest',footerAbout:'हमारे बारे में',footerContact:'संपर्क',footerPrivacy:'गोपनीयता',footerCopy:'© 2026 WanderQuest. सर्वाधिकार सुरक्षित।',viewSat:'उपग्रह दृश्य',hireNow:'किराए पर लें',viewPricing:'मूल्य देखें',challenge:'चुनौती',scamAlerts:'घोटाला चेतावनी',highlights:'मुख्य आकर्षण',perDay:'/दिन',booked:'बुक हो गया!',langTitle:'अपनी भाषा चुनें',close:'बंद करें',completed:'पूर्ण!',locked:'बंद'},
  zh:{heroTag:'🧭 冒险等待着你',heroTitle:'发现世界各地的隐藏宝藏',heroSub:'通过验证价格、当地导游和史诗奖励的寻宝体验。',btnExplore:'探索地图',btnHunt:'开始寻宝',statDest:'目的地',statCountry:'国家',statReward:'奖励',navMap:'地图',navHunt:'寻宝',navPrice:'价格',navGuide:'导游',navReward:'奖励',mapTag:'世界探索者',mapTitle:'互动世界地图',mapDesc:'固定目的地，切换卫星视图，探索全球。',filterAll:'全部',filterCultural:'文化',filterNature:'自然',filterAdventure:'冒险',mapStandard:'标准',mapSatellite:'卫星',huntTag:'寻宝游戏',huntTitle:'收集全球宝藏',huntDesc:'完成挑战以赚取积分和徽章。',priceTag:'验证价格',priceTitle:'避免旅游诈骗',priceDesc:'比较真实的当地价格与虚高的游客价格。',thItem:'项目/服务',thLocal:'当地价格',thTourist:'游客价格',thSave:'节省',guideTag:'当地导游',guideTitle:'聘请可信导游',guideDesc:'预订会说你语言的验证专家。',rewardTag:'你的奖励',rewardTitle:'奖励仪表板',rewardDesc:'跟踪你的积分和徽章。',rwdPoints:'总积分',rwdBadges:'获得徽章',rwdPlaces:'已访问',rwdRank:'探索者等级',badgesTitle:'你的徽章',selectDest:'在地图上选择目的地',footerTag:'WanderQuest',footerAbout:'关于',footerContact:'联系',footerPrivacy:'隐私',footerCopy:'© 2026 WanderQuest. 保留所有权利。',viewSat:'卫星视图',hireNow:'立即聘请',viewPricing:'查看价格',challenge:'挑战',scamAlerts:'诈骗警报',highlights:'亮点',perDay:'/天',booked:'已预订！',langTitle:'选择你的语言',close:'关闭',completed:'已完成！',locked:'未解锁'},
  ja:{heroTag:'🧭 冒険が待っています',heroTitle:'世界中の隠された宝物を発見',heroSub:'検証済み価格、地元ガイド、報酬付きの宝探し体験。',btnExplore:'地図を探索',btnHunt:'ハント開始',statDest:'目的地',statCountry:'国',statReward:'報酬',navMap:'地図',navHunt:'宝探し',navPrice:'価格',navGuide:'ガイド',navReward:'報酬',mapTag:'世界探検家',mapTitle:'インタラクティブ世界地図',mapDesc:'目的地をピン留めして衛星ビューで探索。',filterAll:'すべて',filterCultural:'文化',filterNature:'自然',filterAdventure:'冒険',mapStandard:'標準',mapSatellite:'衛星',huntTag:'宝探し',huntTitle:'世界中の宝物を集めよう',huntDesc:'チャレンジを達成してポイントとバッジを獲得。',priceTag:'検証済み価格',priceTitle:'観光詐欺を回避',priceDesc:'地元価格と観光客価格を比較。',thItem:'項目/サービス',thLocal:'地元価格',thTourist:'観光客価格',thSave:'節約',guideTag:'地元ガイド',guideTitle:'信頼できるガイドを雇用',guideDesc:'あなたの言語を話す専門家を予約。',rewardTag:'あなたの報酬',rewardTitle:'報酬ダッシュボード',rewardDesc:'ポイントとバッジを追跡。',rwdPoints:'合計ポイント',rwdBadges:'獲得バッジ',rwdPlaces:'訪問地',rwdRank:'探検家ランク',badgesTitle:'あなたのバッジ',selectDest:'目的地を選択してください',footerTag:'WanderQuest',footerAbout:'概要',footerContact:'連絡先',footerPrivacy:'プライバシー',footerCopy:'© 2026 WanderQuest. 全著作権所有。',viewSat:'衛星ビュー',hireNow:'今すぐ雇用',viewPricing:'価格を見る',challenge:'チャレンジ',scamAlerts:'詐欺警報',highlights:'ハイライト',perDay:'/日',booked:'予約済み！',langTitle:'言語を選択',close:'閉じる',completed:'完了！',locked:'ロック中'},
  ko:{heroTag:'🧭 모험이 기다립니다',heroTitle:'전 세계 숨겨진 보물을 발견하세요',heroSub:'검증된 가격, 현지 가이드, 보상이 있는 보물찾기 경험.',btnExplore:'지도 탐색',btnHunt:'헌트 시작',statDest:'목적지',statCountry:'국가',statReward:'보상',navMap:'지도',navHunt:'보물찾기',navPrice:'가격',navGuide:'가이드',navReward:'보상',mapTag:'세계 탐험가',mapTitle:'인터랙티브 세계 지도',mapDesc:'목적지를 핀하고 위성 보기로 탐색하세요.',filterAll:'전체',filterCultural:'문화',filterNature:'자연',filterAdventure:'모험',mapStandard:'표준',mapSatellite:'위성',huntTag:'보물찾기',huntTitle:'전 세계 보물 수집',huntDesc:'도전을 완료하여 포인트와 배지를 획득하세요.',priceTag:'검증된 가격',priceTitle:'관광 사기 방지',priceDesc:'현지 가격과 관광객 가격을 비교하세요.',thItem:'항목/서비스',thLocal:'현지 가격',thTourist:'관광객 가격',thSave:'절약',guideTag:'현지 가이드',guideTitle:'신뢰할 수 있는 가이드 고용',guideDesc:'당신의 언어를 구사하는 전문가를 예약하세요.',rewardTag:'당신의 보상',rewardTitle:'보상 대시보드',rewardDesc:'포인트와 배지를 추적하세요.',rwdPoints:'총 포인트',rwdBadges:'획득 배지',rwdPlaces:'방문 장소',rwdRank:'탐험가 등급',badgesTitle:'당신의 배지',selectDest:'지도에서 목적지를 선택하세요',footerTag:'WanderQuest',footerAbout:'소개',footerContact:'연락처',footerPrivacy:'개인정보',footerCopy:'© 2026 WanderQuest. 모든 권리 보유.',viewSat:'위성 보기',hireNow:'지금 고용',viewPricing:'가격 보기',challenge:'도전',scamAlerts:'사기 경고',highlights:'하이라이트',perDay:'/일',booked:'예약됨!',langTitle:'언어를 선택하세요',close:'닫기',completed:'완료!',locked:'잠김'},
  bn:{heroTag:'🧭 আপনার অ্যাডভেঞ্চার অপেক্ষা করছে',heroTitle:'বিশ্বজুড়ে লুকানো ধনসম্পদ আবিষ্কার করুন',heroSub:'যাচাইকৃত মূল্য, স্থানীয় গাইড এবং দারুণ পুরস্কার সহ ট্রেজার হান্ট অভিজ্ঞতা।',btnExplore:'মানচিত্র দেখুন',btnHunt:'হান্ট শুরু',statDest:'গন্তব্য',statCountry:'দেশ',statReward:'পুরস্কার',navMap:'মানচিত্র',navHunt:'ট্রেজার হান্ট',navPrice:'মূল্য',navGuide:'গাইড',navReward:'পুরস্কার',mapTag:'বিশ্ব অনুসন্ধানকারী',mapTitle:'ইন্টারেক্টিভ বিশ্ব মানচিত্র',mapDesc:'যেকোনো গন্তব্য পিন করুন এবং স্যাটেলাইট ভিউতে দেখুন।',filterAll:'সব',filterCultural:'সাংস্কৃতিক',filterNature:'প্রকৃতি',filterAdventure:'অ্যাডভেঞ্চার',mapStandard:'স্ট্যান্ডার্ড',mapSatellite:'স্যাটেলাইট',huntTag:'ট্রেজার হান্ট',huntTitle:'বিশ্বজুড়ে ধনসম্পদ সংগ্রহ করুন',huntDesc:'পয়েন্ট ও ব্যাজ অর্জনের জন্য চ্যালেঞ্জ সম্পন্ন করুন।',priceTag:'যাচাইকৃত মূল্য',priceTitle:'পর্যটক প্রতারণা এড়িয়ে চলুন',priceDesc:'প্রকৃত স্থানীয় মূল্য বনাম পর্যটক মূল্য তুলনা করুন।',thItem:'আইটেম / সেবা',thLocal:'স্থানীয় মূল্য',thTourist:'পর্যটক মূল্য',thSave:'সাশ্রয়',guideTag:'স্থানীয় গাইড',guideTitle:'বিশ্বস্ত গাইড ভাড়া করুন',guideDesc:'আপনার ভাষায় কথা বলা যাচাইকৃত বিশেষজ্ঞ বুক করুন।',rewardTag:'আপনার পুরস্কার',rewardTitle:'পুরস্কার ড্যাশবোর্ড',rewardDesc:'আপনার পয়েন্ট ও ব্যাজ ট্র্যাক করুন।',rwdPoints:'মোট পয়েন্ট',rwdBadges:'অর্জিত ব্যাজ',rwdPlaces:'পরিদর্শিত স্থান',rwdRank:'অনুসন্ধানকারী র‍্যাঙ্ক',badgesTitle:'আপনার ব্যাজ',selectDest:'বিস্তারিত দেখতে মানচিত্রে গন্তব্য নির্বাচন করুন',footerTag:'WanderQuest',footerAbout:'আমাদের সম্পর্কে',footerContact:'যোগাযোগ',footerPrivacy:'গোপনীয়তা',footerCopy:'© 2026 WanderQuest. সর্বস্বত্ব সংরক্ষিত।',viewSat:'স্যাটেলাইট ভিউ',hireNow:'এখনই ভাড়া করুন',viewPricing:'মূল্য দেখুন',challenge:'চ্যালেঞ্জ',scamAlerts:'প্রতারণা সতর্কতা',highlights:'হাইলাইটস',perDay:'/দিন',booked:'বুক হয়েছে!',langTitle:'আপনার ভাষা বেছে নিন',close:'বন্ধ',completed:'সম্পন্ন!',locked:'লক করা'}
};
// Fallback for untranslated languages
Object.keys(LANGS).forEach(k=>{if(!T[k])T[k]=T.en;});

let currentLang = localStorage.getItem('wq-lang') || null;

function t(key) { return (T[currentLang] && T[currentLang][key]) || T.en[key] || key; }

function setLang(lang) {
  currentLang = lang;
  localStorage.setItem('wq-lang', lang);
  document.documentElement.lang = lang;
  if(lang === 'ar') document.body.dir = 'rtl'; else document.body.dir = 'ltr';
  updateAllText();
}

function updateAllText() {
  document.querySelectorAll('[data-t]').forEach(el => {
    el.textContent = t(el.dataset.t);
  });
  document.querySelectorAll('[data-t-html]').forEach(el => {
    el.innerHTML = t(el.dataset.tHtml);
  });
}
